### ISSUE TITLE
Error when trying to upgrade base image to Ubuntu Xenial 16.04

### ISSUE THREAD

**Issue by enriquetuya** [chriswhong/docker-cartodb#36]
@ziprandom  I've seen that you have done the upgrade on your fork. Did it work for you? I'm having a problem that I can't upload any dataset. I've followed your changes here: 

https://github.com/ziprandom/docker-cartodb/commit/b21505145745cd884cd02cfda75d8120bce19166

I'm getting the following error:
```
error_info: {:file_url=>"https://admin.carto.com/uploads/43fd77976e5800e4312e/npfc_recenter.zip"
 :distinct_id=>"admin"
 :username=>"admin"
 :account_type=>"[DEDICATED]"
 :database=>"cartodb_user_a7eaf5d5-d171-44ea-82d3-cd8bfd613af1_db"
 :email=>"dev@example.com"
 :log=>"2018-07-03 15:09:31 UTC: Running on server 4225d35920b8 with PID: 2899\n2018-07-03 15:09:31 UTC: new_importer()\n2018-07-03 15:09:31 UTC: Fetching datasource public_url metadata for item id public/uploads/43fd77976e5800e4312e/npfc_recenter.zip\n2018-07-03 15:09:31 UTC: File will be downloaded from public/uploads/43fd77976e5800e4312e/npfc_recenter.zip\n2018-07-03 15:09:31 UTC: Before importer run\n2018-07-03 15:09:31 UTC: Starting import for public/uploads/43fd77976e5800e4312e/npfc_recenter.zip\n2018-07-03 15:09:31 UTC: Unpacking public/uploads/43fd77976e5800e4312e/npfc_recenter.zip\n2018-07-03 15:09:31 UTC: Filename: /tmp/imports/20180703-2899-isci6x/npfc_recenter/npfc.shp Size (bytes): 187992\n2018-07-03 15:09:31 UTC: Importing data from /tmp/imports/20180703-2899-isci6x/npfc_recenter/npfc.shp\n2018-07-03 15:09:31 UTC: File-based import load\n2018-07-03 15:09:31 UTC: Detected encoding WIN1252\n2018-07-03 15:09:31 UTC: Using database connection with {:adapter=>\"postgres\"
 :encoding=>\"unicode\"
 :host=>\"localhost\"
 :port=>5432
 :database=>\"cartodb_user_a7eaf5d5-d171-44ea-82d3-cd8bfd613af1_db\"
 :username=>\"cartodb_user_a7eaf5d5-d171-44ea-82d3-cd8bfd613af1\"
 :conn_validator_\n2018-07-03 15:09:32 UTC: Errored importing data from /tmp/imports/20180703-2899-isci6x/npfc_recenter/npfc.shp:\n2018-07-03 15:09:32 UTC: Errno::ENOENT: No such file or directory - -f\n2018-07-03 15:09:32 UTC: ----------------------------------------------------\n2018-07-03 15:09:32 UTC: [\"/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/open3.rb:193:in `spawn'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/open3.rb:193:in `popen_run'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/open3.rb:93:in `popen3'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/open3.rb:252:in `capture3'\"

 \"/cartodb/services/importer/lib/importer/ogr2ogr.rb:87:in `run'\"

 \"/cartodb/services/importer/lib/importer/loader.rb:254:in `run_ogr2ogr'\"

 \"/cartodb/services/importer/lib/importer/loader.rb:63:in `block (2 levels) in run'\"

 \"/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\"

 \"/cartodb/services/importer/lib/importer/loader.rb:62:in `block in run'\"

 \"/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\"

 \"/cartodb/services/importer/lib/importer/loader.rb:52:in `run'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:240:in `file_based_loader_run'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:186:in `import'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:380:in `execute_import'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:280:in `block (3 levels) in single_resource_import'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:274:in `each'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:274:in `each_with_index'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:274:in `block (2 levels) in single_resource_import'\"

 \"/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:266:in `block in single_resource_import'\"

 \"/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:244:in `single_resource_import'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:104:in `run_import'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:97:in `block in run'\"

 \"/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\"

 \"/cartodb/services/importer/lib/importer/runner.rb:96:in `run'\"

 \"/cartodb/app/connectors/importer.rb:55:in `run'\"

 \"/cartodb/app/models/data_import.rb:836:in `execute_importer'\"

 \"/cartodb/app/models/data_import.rb:426:in `dispatch'\"

 \"/cartodb/app/models/data_import.rb:189:in `run_import!'\"

 \"/cartodb/lib/resque/importer_jobs.rb:9:in `block in perform'\"

 \"/cartodb/lib/resque/base_job.rb:21:in `call'\"

 \"/cartodb/lib/resque/base_job.rb:21:in `run_action'\"

 \"/cartodb/lib/resque/importer_jobs.rb:9:in `perform'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'\"

 \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'\"

 \"/opt/rubies/ruby-2.2.3/bin/rake:23:in `load'\"

 \"/opt/rubies/ruby-2.2.3/bin/rake:23:in `<main>'\"]\n2018-07-03 15:09:32 UTC: ----------------------------------------------------\n2018-07-03 15:09:32 UTC: Proceeding to register\n2018-07-03 15:09:32 UTC: After importer run\n2018-07-03 15:09:32 UTC: After dispatch\n2018-07-03 15:09:32 UTC: ERROR!\n\n===LOG END==="

 :name=>"npfc"

 :extension=>".shp"

 :success=>false

 :error_code=>99999

 :file_url_hostname=>"admin.carto.com"

 :error_title=>"Unknown"}
stack: ["/cartodb/lib/cartodb/metrics.rb:25:in `report_failure'"

 "/cartodb/lib/cartodb/metrics.rb:16:in `report'"

 "/cartodb/app/models/data_import.rb:1034:in `block in notify'"

 "/cartodb/app/models/data_import.rb:1033:in `each'"

 "/cartodb/app/models/data_import.rb:1033:in `notify'"

 "/cartodb/app/models/data_import.rb:359:in `handle_failure'"

 "/cartodb/app/models/data_import.rb:214:in `run_import!'"

 "/cartodb/lib/resque/importer_jobs.rb:9:in `block in perform'"

 "/cartodb/lib/resque/base_job.rb:21:in `call'"

 "/cartodb/lib/resque/base_job.rb:21:in `run_action'"

 "/cartodb/lib/resque/importer_jobs.rb:9:in `perform'"

 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'"

 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'"

 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'"
 "/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'"
 "/opt/rubies/ruby-2.2.3/bin/rake:23:in `load'"
 "/opt/rubies/ruby-2.2.3/bin/rake:23:in `<main>'"]
```

**Comment by ziprandom** [comment]
@enriquetuya yeah I ran into the exact same problem and still havn't found it's source ..
